//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIS_VOTADOS
    {
        public long RESTAURANTE_ID { get; set; }
        public string NOME { get; set; }
        public Nullable<int> TOTAL { get; set; }
    }
}
