//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRABALHOEntities : DbContext
    {
        public TRABALHOEntities()
            : base("name=TRABALHOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GANHADOR> GANHADOR { get; set; }
        public DbSet<LOGIN> LOGIN { get; set; }
        public DbSet<RESTAURANTE> RESTAURANTE { get; set; }
        public DbSet<VOTACAO> VOTACAO { get; set; }
        public DbSet<GANHADORES> GANHADORES { get; set; }
        public DbSet<MAIS_VOTADOS> MAIS_VOTADOS { get; set; }
        public DbSet<VOTACOES> VOTACOES { get; set; }
    }
}
