//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTACAO
    {
        public long ID { get; set; }
        public long LOGIN_ID { get; set; }
        public long RESTAURANTE_ID { get; set; }
        public System.DateTime DATA { get; set; }
    }
}
